#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
load(url("https://github.com/dgalarraga/Base_spnf_M3/raw/master/spnf.RData"))
library(shiny)
library(dplyr)
library(highcharter)
library(ggplot2)
library(DT)
library(scales)
spnf1 <- as.data.frame(spnf1)
spnf1$Periodo <- seq(as.POSIXct("2000-01-01"), by = "month", length.out = nrow(spnf1))
spnf1[,2:ncol(spnf1)] <- format(spnf1[,2:ncol(spnf1)], digits = 2, nsmall = 2)
spnf1$Periodo2 <- spnf1$Periodo
spnf1$Periodo1 <- as.character(spnf1$Periodo)
spnf1$Periodo <- format(spnf1$Periodo, "%Y-%b")
nombres1 <- colnames(spnf1[-c(1, 3:14, 16:30, 33, 34)])
nombres2 <- colnames(spnf1[c(3,7:14)])
nombres3 <- colnames(spnf1[c(17,20:23,25,29,30)])
tema1 <- theme(panel.background = element_rect(fill = "whitesmoke"), plot.title = element_text(hjust = 0.5, face = "bold"), plot.subtitle = element_text(hjust = 0.5))


ui <- fluidPage(
   # Application title
  tabsetPanel(type = "tabs",
              tabPanel("Agregados",
                       sidebarLayout(
                         sidebarPanel(
                           dateRangeInput("fecha1", "Seleccione la fecha", 
                                          start = spnf1[1,ncol(spnf1)],
                                          end = spnf1[nrow(spnf1),ncol(spnf1)], language = "es"),
                           selectInput("cuenta", "Selecciones la cuenta",
                                       choices = nombres1)
                           ),
                         mainPanel(
                           tabsetPanel(type = "pills",
                                       tabPanel("Cuadro", br(), h3("OPERACIONES DEL SPNF"),br(),dataTableOutput("variables")),
                                       tabPanel("Grafico", plotOutput("grafico"))
                           ))
                       )), 
              tabPanel("Ingresos",
                       sidebarLayout(
                         sidebarPanel(
                           dateRangeInput("fecha2", "Seleccione la fecha", 
                                          start = spnf1[1,ncol(spnf1)],
                                          end = spnf1[nrow(spnf1),ncol(spnf1)], language = "es"),
                           selectInput("ingresos", "Selecciones la cuenta",
                                       choices = nombres2)
                         ),
                         mainPanel(
                           tabsetPanel(type = "pills",
                                       tabPanel("Cuadro", br(), h3("INGRESOS DEL SPNF"),br(),dataTableOutput("tabla")),
                                       tabPanel("Grafico", plotOutput("grafico1"))
                                       ))
                         )),
              tabPanel("Gastos",
                       sidebarLayout(
                         sidebarPanel(
                           dateRangeInput("fecha3", "Seleccione la fecha", 
                                          start = spnf1[1,ncol(spnf1)],
                                          end = spnf1[nrow(spnf1),ncol(spnf1)], language = "es"),
                           selectInput("gastos", "Selecciones la cuenta",
                                       choices = nombres3)
                         ),
                         mainPanel(
                           tabsetPanel(type = "pills",
                                       tabPanel("Cuadro", br(), h3("GASTOS DEL SPNF"),br(),dataTableOutput("tabla1")),
                                       tabPanel("Grafico", plotOutput("grafico2"))
                                       ))
                         ))
  ))
  
  
##### Define server logic required to draw a histogram
server <- function(input, output) {
  
  formula1 <- reactive({
    tablarango <- spnf1[spnf1$Periodo1 >= input$fecha1[1] & spnf1$Periodo1<= input$fecha1[2], c("Periodo", "Periodo1", "Periodo2", input$cuenta)]
    return(tablarango)
  })
  
  formula2 <- reactive({
    tablarango <- spnf1[spnf1$Periodo1 >= input$fecha2[1] & spnf1$Periodo1<= input$fecha2[2], c("Periodo", "Periodo1", "Periodo2", input$ingresos)]
    return(tablarango)
  })
    
  formula3 <- reactive({
    tablarango <- spnf1[spnf1$Periodo1 >= input$fecha3[1] & spnf1$Periodo1<= input$fecha3[2], c("Periodo", "Periodo1", "Periodo2", input$gastos)]
    return(tablarango)
  })
     
  
   output$variables <- renderDataTable({
    datatable(formula1()[,c("Periodo", input$cuenta)], options = list(pageLength = 12, language = list(url = "//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json")), 
                          rownames = FALSE)})
   
   output$grafico <- renderPlot({
    ggplot(formula1(), aes(x = formula1()[,"Periodo2"] , y = as.numeric(formula1()[,input$cuenta]))) + geom_line(color = "dodgerblue3") + labs(title = "OPERACIONES DEL SPNF", subtitle = input$cuenta, x = "\nPeriodo", y = "USD Miles") +
       scale_x_datetime(breaks = date_breaks("6 month"), labels = date_format(format = "%y-%b")) + tema1})
   
   output$tabla <- renderDataTable({
     datatable(formula2()[,c("Periodo", input$ingresos)], options = list(pageLength = 12, language = list(url = "//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json")), 
               rownames = FALSE)})
   
   output$grafico1 <- renderPlot({
     ggplot(formula2(), aes(x = formula2()[,"Periodo2"] , y = as.numeric(formula2()[,input$ingresos]))) + geom_line(color = "tomato1") + labs(title = "INGRESOS DEL SPNF", subtitle = input$ingresos, x = "\nPeriodo", y = "USD Miles") +
       scale_x_datetime(breaks = date_breaks("6 month"), labels = date_format(format = "%y-%b")) + tema1})
   
   output$tabla1 <- renderDataTable({
     datatable(formula3()[,c("Periodo", input$gastos)], options = list(pageLength = 12, language = list(url = "//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json")), 
               rownames = FALSE)})
   
   output$grafico2 <- renderPlot({
     ggplot(formula3(), aes(x = formula3()[,"Periodo2"] , y = as.numeric(formula3()[,input$gastos]))) + geom_line(color = "purple3") + labs(title = "GASTOS DEL SPNF", subtitle = input$gastos, x = "\nPeriodo", y = "USD Miles") +
       scale_x_datetime(breaks = date_breaks("6 month"), labels = date_format(format = "%y-%b")) + tema1})
   
}

  
# Run the application 
shinyApp(ui = ui, server = server)

